---
# defaults file for mysql
mysql_databases: []
mysql_users: []
mysql_root_username: root
mysql_root_home: /root
mysql_root_password: secret
mysql_root_password_update: no

mysql_daemon: mariadb
mysql_packages:
  - mariadb
  - mariadb-server
  - mariadb-libs
  - MySQL-python
  - perl-DBD-MySQL

mysql_config_file: /etc/my.cnf
mysql_config_include_dir: /etc/my.cnf.d
mysql_datadir: /var/lib/mysql
mysql_port: "3306"
mysql_socket: /var/lib/mysql/mysql.sock
mysql_bind_address: '0.0.0.0'
mysql_pid_file: /var/run/mariadb/mariadb.pid

mysql_log_error: /var/log/mariadb/mariadb.log
mysql_slow_query_log_file: /var/log/mysql-slow.log
mysql_slow_query_time: "2"

mysql_key_buffer_size: "256M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_myisam_sort_buffer_size: "64M"
mysql_thread_cache_size: "8"
mysql_query_cache_type: "0"
mysql_query_cache_size: "16M"
mysql_query_cache_limit: "1M"
mysql_max_connections: "151"
mysql_tmp_table_size: "16M"
mysql_max_heap_table_size: "16M"
mysql_group_concat_max_len: "1024"
mysql_join_buffer_size: "262144"

mysql_lower_case_table_names: "0"
mysql_wait_timeout: "28800"
mysql_event_scheduler_state: "OFF"

mysql_innodb_large_prefix: "1"
mysql_innodb_file_format: "barracuda"
mysql_innodb_file_per_table: "1"
# Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
mysql_innodb_buffer_pool_size: "256M"
# Set .._log_file_size to 25% of buffer pool size.
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "1"
mysql_innodb_lock_wait_timeout: "50"

mysql_mysqldump_max_allowed_packet: "64M"
