---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: bento/centos-7.3
      box: bento/centos-7.3
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: mysql
      ansible_groups:
        - group1
verifier:
  name: testinfra
  options:
    v: 1
